### ISSUE TITLE
运行环境同 readme, simcse_loss 中 `K.eye(K.shape(y_pred)[0])` 在 `encoder.compile` 时直接卡死

### ISSUE THREAD

**Issue by ericxsun** [bojone/SimCSE#1]

**Comment by bojone** [comment]
你试试 K.eye(K.shape(y_pred)[0]) 改为 tf.eye(K.shape(y_pred)[0])，我昨天试了一个环境也在这句报错了～

**Comment by ericxsun** [comment]
> 你试试 K.eye(K.shape(y_pred)[0]) 改为 tf.eye(K.shape(y_pred)[0])，我昨天试了一个环境也在这句报错了～

非常感谢，可以正确运行了。
